### ISSUE TITLE
About the example latex code

### ISSUE THREAD

**Issue by t-cool** [tectonic-typesetting/tectonic-ruby#1]
Hi.
I've successfully installed tectonic-ruby.
When I try using it on irb, I faced with the following error:
Could you tell me how to compile a latex code to make a pdf file?

```
gem specific_install https://github.com/tectonic-typesetting/tectonic-ruby
brew install --only-dependencies --build-from-source tectonic
export DEP_OPENSSL_INCLUDE=$(brew --prefix openssl)/include
export PKG_CONFIG_PATH=$(brew --prefix icu4c)/lib/pkgconfig
gem install specific_install
gem specific_install https://github.com/tectonic-typesetting/tectonic-ruby

Compiling tectonic_ruby v0.1.0 (/Users/noguchihiroki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/tectonic-0.1.0)
    Finished release [optimized] target(s) in 2m 19s                  
Successfully installed

irb

$ irb
irb(main):001:0> require 'tectonic'
=> true
irb(main):002:0> latex = <<-EOS
irb(main):003:0" \usepackage{article}
irb(main):004:0" \begin{document}
irb(main):005:0" Hello, Tectonic!
irb(main):006:0" \end{document}
irb(main):007:0" EOS
Traceback (most recent call last):
        1: from /Users/noguchihiroki/.rbenv/versions/2.5.0/bin/irb:11:in `<main>'
SyntaxError ((irb):3: invalid Unicode escape
\usepackage{article}
  ^
(irb):2: syntax error, unexpected end-of-input, expecting tSTRING_CONTENT or tSTRING_DBEG or tSTRING_DVAR or tSTRING_END
latex = <<-EOS
              ^)
```

My local environment is as bellow:
macOS High Sierra(10.13.6)
$ ruby --version
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
$ rustc --version
rustc 1.31.1 (b6c32da9b 2018-12-18)
$ tectonic --version
Tectonic 0.1.11

I'd appreciate your help.

t-cool

**Comment by ta2gch** [comment]
Thank you for a report.
You can type that string with double back slash, like the follows.

```ruby
latex = <<-EOS
\\usepackage{article}
\\begin{document}
Hello, Tectonic!
\\end{document}
EOS
```

I'll fix it in all documents
Cheers!

**Comment by t-cool** [comment]
Thank you for your advice!
Will the following code generate a pdf file in pwd?
`pdf = Tectonic.latex_to_pdf(latex)`
When I execute the code, Terminal's screen is blinking, but nothing is generated.

**Comment by ta2gch** [comment]
The `pdf` is octes (i.e., bytes) and there are no data in the file system in that time.
You can get the file by writing with `File.binwrite("out.pdf", pdf)`.

**Comment by t-cool** [comment]
I made `example.app` inside the `tectonic-ruby` folder and run it through `ruby example.rb`

```
require 'tectonic'

latex = <<-EOS
\\usepackage{article}
\\begin{document}
Hello, Tectonic!
\\end{document}
EOS

pdf = Tectonic.latex_to_pdf(latex)

File.binwrite("out.pdf", pdf)
```

The file "out.pdf" was generated, but the file is blank.

Could you tell me how to solve this problem?

**Comment by ta2gch** [comment]
I'm sorry, I had two errors in my comments.

1. You need to convert octets to raw data(I don't know the right name), with `pdf.pack("C*")`
2. In latex code, you should `documentclass` instead of `usepackage`

Therefore, the perfect code is this.

```ruby
require 'tectonic'

latex = <<-EOS
\\documentclass{article}
\\begin{document}
Hello, Tectonic!
\\end{document}
EOS

pdf = Tectonic.latex_to_pdf(latex)

File.binwrite("out.pdf", pdf.pack("C*"))
```

**Comment by t-cool** [comment]
I made it owing to your advice!
I really appreciate it!
